version: "3.9"

services:
  postgres:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - env
    expose:
      - 5432
    ports:
      - 5433:5432
    networks:
      - pgnet

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/construction
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env
    environment:
      DEPLOYMENT: api
      COMPOSE_HTTP_TIMEOUT: 3600
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      - pgnet

volumes:
  pgdata:
  esdata1:
    driver: local
networks:
  pgnet: