# Generated by Django 5.0.2 on 2024-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0017_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('store_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.storeuser')),
            ],
        ),
    ]
